version: '3.8'

services:
  api:
    build: ./backend
    container_name: unidal_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+mysqlconnector://unidal:admin_135@db/unidal
    volumes:
      - ./backend:/app
      - ./alembic.ini:/app/alembic.ini
    # command: ["sh", "-c", "PYTHONPATH=. python app/create_tables.py && PYTHONPATH=. uvicorn app.main:app --host 0.0.0.0 --port 8000"]

  db:
    image: mysql:8
    container_name: unidal_db
    restart: always
    environment:
      MYSQL_DATABASE: unidal
      MYSQL_ROOT_PASSWORD: admin_135
      MYSQL_USER: unidal
      MYSQL_PASSWORD: admin_135
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000
    container_name: unidal_frontend
    ports:
      - "3010:80"
    depends_on:
      - api
    volumes:
    - ./frontend:/app
    - /app/node_modules  # evita sobrescrever o node_modules do container
    restart: always

volumes:
  db_data:
