"""Add empresa to users

Revision ID: 57446dd2c7e9
Revises: d3bae00142a3
Create Date: 2025-07-31 10:55:04.957814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '57446dd2c7e9'
down_revision: Union[str, None] = 'd3bae00142a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registros_hora', 'usuario_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('registros_hora', 'projeto_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('registros_hora', 'metros_quadrados',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('users', sa.Column('empresa', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'empresa')
    op.alter_column('registros_hora', 'metros_quadrados',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('registros_hora', 'projeto_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('registros_hora', 'usuario_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
