"""add RegistroHoraEquipa table

Revision ID: d3bae00142a3
Revises: xxxx
Create Date: 2025-07-13 16:14:56.443121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3bae00142a3'
down_revision: Union[str, None] = 'xxxx'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registros_hora', 'preparacao',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('registros_hora', 'bruto',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('registros_hora', 'colagem',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('registros_hora', 'acabamento',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('registros_hora', 'serragem',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('registros_hora', 'intervencao_maquinas',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('registros_hora_equipa', 'registro_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('registros_hora_equipa', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_registros_hora_equipa_id'), 'registros_hora_equipa', ['id'], unique=False)
    op.drop_constraint(op.f('registros_hora_equipa_ibfk_2'), 'registros_hora_equipa', type_='foreignkey')
    op.drop_constraint(op.f('registros_hora_equipa_ibfk_1'), 'registros_hora_equipa', type_='foreignkey')
    op.create_foreign_key(None, 'registros_hora_equipa', 'registros_hora', ['registro_id'], ['id'])
    op.create_foreign_key(None, 'registros_hora_equipa', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registros_hora_equipa', type_='foreignkey')
    op.drop_constraint(None, 'registros_hora_equipa', type_='foreignkey')
    op.create_foreign_key(op.f('registros_hora_equipa_ibfk_1'), 'registros_hora_equipa', 'registros_hora', ['registro_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('registros_hora_equipa_ibfk_2'), 'registros_hora_equipa', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_registros_hora_equipa_id'), table_name='registros_hora_equipa')
    op.alter_column('registros_hora_equipa', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('registros_hora_equipa', 'registro_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('registros_hora', 'intervencao_maquinas',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('registros_hora', 'serragem',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('registros_hora', 'acabamento',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('registros_hora', 'colagem',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('registros_hora', 'bruto',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('registros_hora', 'preparacao',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
