import { useEffect, useMemo, useState } from "react";
import { Boxes, ClipboardList, PackagePlus, Warehouse } from "lucide-react";
import api from "@/services/api";
import { useAuth } from "@/context/AuthContext";

type Material = { id:number; nome:string; unidade:string; estoque_fisico:number|string; estoque_minimo:number|string; is_active:boolean };
type Item = { id:number; material_solicitado_id:number; material_enviado_id?:number|null; quantidade_solicitada:number|string; quantidade_enviada:number|string; motivo_substituicao?:string|null };
type Pedido = { id:number; solicitante_id:number; status:string; resultado?:string|null; observacao?:string|null; motivo_conclusao_parcial?:string|null; itens:Item[] };

const n=(v:number|string)=>Number(v||0);
const Estaleiro=()=>{
 const {user}=useAuth();
 const [materiais,setMateriais]=useState<Material[]>([]);
 const [pedidos,setPedidos]=useState<Pedido[]>([]);
 const [erro,setErro]=useState("");
 const [novoMaterial,setNovoMaterial]=useState({nome:"",unidade:"un",estoque_inicial:"0",estoque_minimo:"0"});
 const [pedidoItens,setPedidoItens]=useState([{material_id:"",quantidade:"1"}]);
 const [observacao,setObservacao]=useState("");
 const [buscaEstoque,setBuscaEstoque]=useState("");
 const [paginaEstoque,setPaginaEstoque]=useState(1);
 const porPagina=20;
 const funcoes=user?.funcoes||[];
 const admin=user?.perfil==="admin";
 const chefe=admin||funcoes.some(f=>f.codigo==="CHEFE_EQUIPE"&&f.is_active);
 const responsavel=admin||funcoes.some(f=>f.codigo==="RESPONSAVEL_ESTALEIRO"&&f.is_active);
 const nomeMaterial=(id?:number|null)=>materiais.find(m=>m.id===id)?.nome||`#${id}`;
 const carregar=async()=>{try{setErro("");const [m,p]=await Promise.all([api.get("/materiais/catalogo"),api.get("/materiais/pedidos")]);setMateriais(m.data);setPedidos(p.data)}catch(e:any){setErro(e?.response?.data?.detail||"Não foi possível carregar o estaleiro.")}};
 useEffect(()=>{carregar()},[]);
 const alertas=useMemo(()=>materiais.filter(m=>n(m.estoque_fisico)<=n(m.estoque_minimo)),[materiais]);
 const materiaisFiltrados=useMemo(()=>materiais.filter(m=>m.nome.toLowerCase().includes(buscaEstoque.toLowerCase())),[materiais,buscaEstoque]);
 const totalPaginas=Math.max(1,Math.ceil(materiaisFiltrados.length/porPagina));
 const materiaisPagina=materiaisFiltrados.slice((paginaEstoque-1)*porPagina,paginaEstoque*porPagina);
 const entrada=async(m:Material)=>{const q=prompt(`Quantidade recebida de ${m.nome}:`,"");if(!q)return;const obs=prompt("Observação da entrada (fornecedor, documento, etc.):","")||null;try{await api.post(`/materiais/catalogo/${m.id}/entrada`,{quantidade:Number(q),observacao:obs});carregar()}catch(e:any){alert(e?.response?.data?.detail||"Erro ao registrar entrada.")}};
 const editar=async(m:Material)=>{const nome=prompt("Nome do material:",m.nome);if(!nome)return;const unidade=prompt("Unidade de medida:",m.unidade);if(!unidade)return;const minimo=prompt("Estoque mínimo para alerta:",String(m.estoque_minimo));if(minimo===null)return;try{await api.put(`/materiais/catalogo/${m.id}`,{nome,unidade,estoque_minimo:Number(minimo)});carregar()}catch(e:any){alert(e?.response?.data?.detail||"Erro ao editar material.")}};
 const ajustar=async(m:Material)=>{const qtd=prompt(`Quantidade física contada de ${m.nome}:`,String(m.estoque_fisico));if(qtd===null)return;const motivo=prompt("Motivo obrigatório do ajuste:","");if(!motivo)return;try{await api.post(`/materiais/catalogo/${m.id}/ajuste`,{estoque_fisico:Number(qtd),motivo});carregar()}catch(e:any){alert(e?.response?.data?.detail||"Erro ao ajustar estoque.")}};
 const criarMaterial=async(e:any)=>{e.preventDefault();try{await api.post("/materiais/catalogo",{...novoMaterial,estoque_inicial:Number(novoMaterial.estoque_inicial),estoque_minimo:Number(novoMaterial.estoque_minimo)});setNovoMaterial({nome:"",unidade:"un",estoque_inicial:"0",estoque_minimo:"0"});carregar()}catch(e:any){alert(e?.response?.data?.detail||"Erro ao cadastrar material.")}};
 const criarPedido=async(e:any)=>{e.preventDefault();const itens=pedidoItens.filter(i=>i.material_id).map(i=>({material_id:Number(i.material_id),quantidade:Number(i.quantidade)}));if(!itens.length)return alert("Adicione pelo menos um material.");try{await api.post("/materiais/pedidos",{itens,observacao:observacao||null});setPedidoItens([{material_id:"",quantidade:"1"}]);setObservacao("");carregar()}catch(e:any){alert(e?.response?.data?.detail||"Erro ao criar pedido.")}};
 const atender=async(p:Pedido,i:Item)=>{const q=prompt("Quantidade enviada:",String(i.quantidade_solicitada));if(q===null)return;const sub=prompt("ID do material substituto (deixe vazio para o solicitado):","");let motivo:string|null=null;if(sub)motivo=prompt("Motivo da substituição:","")||"";try{await api.put(`/materiais/pedidos/${p.id}/itens/${i.id}`,{quantidade_enviada:Number(q),material_enviado_id:sub?Number(sub):null,motivo_substituicao:motivo});carregar()}catch(e:any){alert(e?.response?.data?.detail||"Erro ao atender item.")}};
 const concluir=async(p:Pedido)=>{const parcial=p.itens.some(i=>n(i.quantidade_enviada)<n(i.quantidade_solicitada));const motivo=parcial?prompt("Este pedido está parcial. Informe o motivo:",""):null;if(parcial&&!motivo)return;try{await api.post(`/materiais/pedidos/${p.id}/concluir`,{motivo_parcial:motivo});carregar()}catch(e:any){alert(e?.response?.data?.detail||"Erro ao concluir pedido.")}};
 return <div className="p-4 md:p-6 space-y-6">
  <div><h1 className="text-2xl font-bold text-gray-800 flex items-center gap-2"><Warehouse size={26}/>Estaleiro</h1><p className="text-gray-500">Pedidos de materiais, preparação e controle de estoque.</p></div>
  {erro&&<div className="rounded border border-red-200 bg-red-50 p-3 text-red-700">{erro}</div>}
  {responsavel&&alertas.length>0&&<div className="rounded-lg border border-amber-200 bg-amber-50 p-4"><b>Estoque baixo:</b> {alertas.map(m=>`${m.nome} (${m.estoque_fisico} ${m.unidade})`).join(", ")}</div>}
  <div className="grid gap-6 xl:grid-cols-2">
   {chefe&&<form onSubmit={criarPedido} className="rounded-lg bg-white p-5 shadow"><h2 className="mb-4 font-semibold flex gap-2"><ClipboardList size={20}/>Novo pedido</h2>
    {pedidoItens.map((it,idx)=><div key={idx} className="mb-3 grid grid-cols-[1fr_120px_40px] gap-2"><select className="border rounded px-3 py-2" value={it.material_id} onChange={e=>setPedidoItens(v=>v.map((x,j)=>j===idx?{...x,material_id:e.target.value}:x))}><option value="">Selecione o material</option>{materiais.map(m=><option key={m.id} value={m.id}>{m.nome} — disponível {m.estoque_fisico} {m.unidade}</option>)}</select><input className="border rounded px-3 py-2" type="number" min=".001" step=".001" value={it.quantidade} onChange={e=>setPedidoItens(v=>v.map((x,j)=>j===idx?{...x,quantidade:e.target.value}:x))}/><button type="button" className="text-red-500" onClick={()=>setPedidoItens(v=>v.filter((_,j)=>j!==idx))}>×</button></div>)}
    <button type="button" className="text-indigo-600 text-sm" onClick={()=>setPedidoItens(v=>[...v,{material_id:"",quantidade:"1"}])}>+ Adicionar item</button>
    <textarea className="mt-3 w-full border rounded p-2" placeholder="Observação do pedido (opcional)" value={observacao} onChange={e=>setObservacao(e.target.value)}/>
    <button className="mt-3 rounded bg-indigo-600 px-4 py-2 text-white">Enviar pedido</button>
   </form>}
   {responsavel&&<form onSubmit={criarMaterial} className="rounded-lg bg-white p-5 shadow"><h2 className="mb-1 font-semibold flex gap-2"><PackagePlus size={20}/>Cadastrar novo material</h2><p className="mb-4 text-sm text-gray-500">Use somente para um material que ainda não existe. Para reposição, use “Entrada” na tabela de estoque.</p><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Nome do material<input required className="mt-1 w-full border rounded px-3 py-2 font-normal" placeholder="Ex.: Luvas nitrilo" value={novoMaterial.nome} onChange={e=>setNovoMaterial({...novoMaterial,nome:e.target.value})}/></label><label className="text-sm font-medium">Unidade de medida<input required className="mt-1 w-full border rounded px-3 py-2 font-normal" placeholder="Ex.: un, par, caixa, kg" value={novoMaterial.unidade} onChange={e=>setNovoMaterial({...novoMaterial,unidade:e.target.value})}/></label><label className="text-sm font-medium">Quantidade inicial em estoque<input className="mt-1 w-full border rounded px-3 py-2 font-normal" type="number" min="0" step=".001" value={novoMaterial.estoque_inicial} onChange={e=>setNovoMaterial({...novoMaterial,estoque_inicial:e.target.value})}/><span className="block mt-1 text-xs text-gray-500">Quantidade disponível no momento do primeiro cadastro.</span></label><label className="text-sm font-medium">Estoque mínimo para alerta<input className="mt-1 w-full border rounded px-3 py-2 font-normal" type="number" min="0" step=".001" value={novoMaterial.estoque_minimo} onChange={e=>setNovoMaterial({...novoMaterial,estoque_minimo:e.target.value})}/><span className="block mt-1 text-xs text-gray-500">Ao atingir este valor, o sistema sinaliza estoque baixo.</span></label></div><button className="mt-4 rounded bg-indigo-600 px-4 py-2 text-white">Cadastrar novo material</button></form>}
  </div>
  {responsavel&&<section className="rounded-lg bg-white p-5 shadow"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold flex gap-2"><Boxes size={20}/>Estoque</h2><p className="text-sm text-gray-500">{materiaisFiltrados.length} materiais encontrados • 20 por página</p></div><input className="w-full sm:w-72 border rounded px-3 py-2" placeholder="Pesquisar material..." value={buscaEstoque} onChange={e=>{setBuscaEstoque(e.target.value);setPaginaEstoque(1)}}/></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Material</th><th>Unidade</th><th>Estoque</th><th>Mínimo</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{materiaisPagina.map(m=><tr key={m.id} className="border-b"><td className="p-2 font-medium">{m.nome}</td><td>{m.unidade}</td><td>{m.estoque_fisico}</td><td>{m.estoque_minimo}</td><td>{n(m.estoque_fisico)<=n(m.estoque_minimo)?<span className="text-amber-700 font-medium">Baixo</span>:"Normal"}</td><td className="py-2 whitespace-nowrap"><button className="mr-3 font-medium text-emerald-700" onClick={()=>entrada(m)}>+ Entrada</button><button className="mr-3 text-indigo-600" onClick={()=>editar(m)}>Editar</button><button className="text-gray-600" onClick={()=>ajustar(m)}>Ajustar</button></td></tr>)}</tbody></table></div><div className="mt-4 flex items-center justify-between text-sm"><button disabled={paginaEstoque<=1} className="rounded border px-3 py-1 disabled:opacity-40" onClick={()=>setPaginaEstoque(p=>Math.max(1,p-1))}>Anterior</button><span>Página {Math.min(paginaEstoque,totalPaginas)} de {totalPaginas}</span><button disabled={paginaEstoque>=totalPaginas} className="rounded border px-3 py-1 disabled:opacity-40" onClick={()=>setPaginaEstoque(p=>Math.min(totalPaginas,p+1))}>Próxima</button></div></section>}
  <section className="rounded-lg bg-white p-5 shadow"><h2 className="mb-4 font-semibold">Pedidos</h2><div className="space-y-4">{pedidos.length===0&&<p className="text-gray-500">Nenhum pedido.</p>}{pedidos.map(p=><div key={p.id} className="rounded border p-4"><div className="flex flex-wrap justify-between gap-2"><div><b>Pedido #{p.id}</b> <span className="ml-2 text-sm text-gray-500">{p.status}</span>{p.resultado&&<span className="ml-2 rounded bg-gray-100 px-2 py-1 text-xs">{p.resultado}</span>}</div>{responsavel&&p.status!=="CONCLUIDO"&&<button onClick={()=>concluir(p)} className="rounded bg-emerald-600 px-3 py-1 text-sm text-white">Concluir pedido</button>}</div>{p.observacao&&<p className="mt-2 text-sm text-gray-600">{p.observacao}</p>}<div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="py-1">Solicitado</th><th>Qtd.</th><th>Enviado</th><th>Qtd.</th>{responsavel&&<th>Ação</th>}</tr></thead><tbody>{p.itens.map(i=><tr key={i.id} className="border-b"><td className="py-2">{nomeMaterial(i.material_solicitado_id)}</td><td>{i.quantidade_solicitada}</td><td>{i.material_enviado_id?nomeMaterial(i.material_enviado_id):"—"}{i.motivo_substituicao&&<div className="text-xs text-gray-500">{i.motivo_substituicao}</div>}</td><td>{i.quantidade_enviada}</td>{responsavel&&<td><button disabled={p.status==="CONCLUIDO"} onClick={()=>atender(p,i)} className="text-indigo-600 disabled:text-gray-300">Atender</button></td>}</tr>)}</tbody></table></div>{p.motivo_conclusao_parcial&&<p className="mt-2 text-sm text-amber-700">Conclusão parcial: {p.motivo_conclusao_parcial}</p>}</div>)}</div></section>
 </div>
};
export default Estaleiro;
