import { useEffect, useMemo, useState } from "react";
import { Boxes, ClipboardList, PackagePlus, Printer, Warehouse } from "lucide-react";
import api from "@/services/api";
import { useAuth } from "@/context/AuthContext";
import Modal from "@/components/ui/modal";
import MaterialSearch from "@/components/MaterialSearch";

type Tamanho={id:number;tamanho:string;estoque_fisico:number|string;estoque_minimo:number|string;estoque_reservado:number|string;estoque_disponivel:number|string};
type Material={id:number;nome:string;unidade:string;estoque_fisico:number|string;estoque_reservado:number|string;estoque_disponivel:number|string;estoque_minimo:number|string;controla_tamanho:boolean;tamanhos:Tamanho[];is_active:boolean};
type Movimento={id:number;material_id:number;pedido_id?:number|null;usuario_nome?:string|null;tipo:string;quantidade:number|string;tamanho?:string|null;observacao?:string|null;criado_em:string};
type Item={id:number;material_solicitado_id:number;material_enviado_id?:number|null;tamanho_solicitado?:string|null;tamanho_enviado?:string|null;quantidade_solicitada:number|string;quantidade_enviada:number|string;motivo_substituicao?:string|null};
type Pedido={id:number;solicitante_id:number;status:string;resultado?:string|null;observacao?:string|null;motivo_conclusao_parcial?:string|null;criado_em:string;itens:Item[]};
type PedidoFormItem={material_id:string;tamanho:string;quantidade:string};
const n=(v:number|string)=>Number(v||0); const inteiro=(v:number|string)=>Math.trunc(n(v));

const Estaleiro=()=>{
 const {user}=useAuth(); const [materiais,setMateriais]=useState<Material[]>([]); const [pedidos,setPedidos]=useState<Pedido[]>([]); const [erro,setErro]=useState("");
 const [novoMaterial,setNovoMaterial]=useState({nome:"",unidade:"un",estoque_inicial:"0",estoque_minimo:"0",controla_tamanho:false,tamanhos:""});
 const [pedidoItens,setPedidoItens]=useState<PedidoFormItem[]>([{material_id:"",tamanho:"",quantidade:"1"}]); const [observacao,setObservacao]=useState("");
 const [buscaEstoque,setBuscaEstoque]=useState(""); const [paginaEstoque,setPaginaEstoque]=useState(1); const [estoqueModal,setEstoqueModal]=useState<{tipo:"entrada"|"editar"|"ajustar";material:Material}|null>(null);
 const [estoqueForm,setEstoqueForm]=useState({quantidade:"",observacao:"",nome:"",unidade:"",minimo:"",motivo:"",tamanho:""}); const [estoqueErro,setEstoqueErro]=useState(""); const [movimentos,setMovimentos]=useState<Movimento[]>([]);
 const [pedidoErro,setPedidoErro]=useState(""); const [atenderModal,setAtenderModal]=useState<{pedido:Pedido;item:Item}|null>(null); const [atenderForm,setAtenderForm]=useState({quantidade:"",material_id:"",tamanho:"",motivo:""}); const [concluirModal,setConcluirModal]=useState<Pedido|null>(null); const [motivoParcial,setMotivoParcial]=useState("");
 const porPagina=20; const funcoes=user?.funcoes||[]; const admin=user?.perfil==="admin"; const chefe=admin||funcoes.some(f=>f.codigo==="CHEFE_EQUIPE"&&f.is_active); const responsavel=admin||funcoes.some(f=>f.codigo==="RESPONSAVEL_ESTALEIRO"&&f.is_active);
 const mat=(id?:number|null)=>materiais.find(m=>m.id===id); const nomeMaterial=(id?:number|null)=>mat(id)?.nome||`#${id}`;
 const carregar=async()=>{try{setErro("");const reqs:any[]=[api.get("/materiais/catalogo"),api.get("/materiais/pedidos")];if(responsavel)reqs.push(api.get("/materiais/movimentos?limite=100"));const [m,p,mov]=await Promise.all(reqs);setMateriais(m.data);setPedidos(p.data);if(mov)setMovimentos(mov.data)}catch(e:any){setErro(e?.response?.data?.detail||"Não foi possível carregar o armazém.")}}; useEffect(()=>{carregar()},[]);
 const alertas=useMemo(()=>materiais.filter(m=>!m.controla_tamanho&&n(m.estoque_disponivel)<=n(m.estoque_minimo)||m.controla_tamanho&&m.tamanhos.some(t=>n(t.estoque_disponivel)<=n(t.estoque_minimo))),[materiais]);
 const materiaisFiltrados=useMemo(()=>materiais.filter(m=>m.nome.toLowerCase().includes(buscaEstoque.toLowerCase())),[materiais,buscaEstoque]); const totalPaginas=Math.max(1,Math.ceil(materiaisFiltrados.length/porPagina)); const materiaisPagina=materiaisFiltrados.slice((paginaEstoque-1)*porPagina,paginaEstoque*porPagina);
 const abrirEstoqueModal=(tipo:"entrada"|"editar"|"ajustar",m:Material)=>{setEstoqueErro("");const tam=m.controla_tamanho?m.tamanhos[0]?.tamanho||"":"";const fisico=m.controla_tamanho?m.tamanhos[0]?.estoque_fisico:m.estoque_fisico;setEstoqueModal({tipo,material:m});setEstoqueForm({quantidade:tipo==="ajustar"?String(inteiro(fisico||0)):"",observacao:"",nome:m.nome,unidade:m.unidade,minimo:String(inteiro(m.estoque_minimo)),motivo:"",tamanho:tam})};
 const salvarEstoqueModal=async()=>{if(!estoqueModal)return;setEstoqueErro("");const m=estoqueModal.material;if(estoqueModal.tipo==="ajustar"&&!estoqueForm.motivo.trim()){setEstoqueErro("Informe o motivo do ajuste.");return}try{if(estoqueModal.tipo==="entrada")await api.post(`/materiais/catalogo/${m.id}/entrada`,{quantidade:inteiro(estoqueForm.quantidade),tamanho:m.controla_tamanho?estoqueForm.tamanho:null,observacao:estoqueForm.observacao||null});if(estoqueModal.tipo==="editar")await api.put(`/materiais/catalogo/${m.id}`,{nome:estoqueForm.nome,unidade:estoqueForm.unidade,estoque_minimo:inteiro(estoqueForm.minimo)});if(estoqueModal.tipo==="ajustar")await api.post(`/materiais/catalogo/${m.id}/ajuste`,{estoque_fisico:inteiro(estoqueForm.quantidade),tamanho:m.controla_tamanho?estoqueForm.tamanho:null,motivo:estoqueForm.motivo});setEstoqueModal(null);carregar()}catch(e:any){setEstoqueErro(e?.response?.data?.detail||"Não foi possível guardar a alteração.")}};
 const criarMaterial=async(e:any)=>{e.preventDefault();try{const tamanhos=novoMaterial.controla_tamanho?novoMaterial.tamanhos.split(/[,;\n]/).map(x=>x.trim()).filter(Boolean).map(tamanho=>({tamanho,estoque_inicial:0,estoque_minimo:0})):[];await api.post("/materiais/catalogo",{nome:novoMaterial.nome,unidade:novoMaterial.unidade,estoque_inicial:novoMaterial.controla_tamanho?0:inteiro(novoMaterial.estoque_inicial),estoque_minimo:inteiro(novoMaterial.estoque_minimo),controla_tamanho:novoMaterial.controla_tamanho,tamanhos});setNovoMaterial({nome:"",unidade:"un",estoque_inicial:"0",estoque_minimo:"0",controla_tamanho:false,tamanhos:""});carregar()}catch(e:any){alert(e?.response?.data?.detail||"Erro ao cadastrar material.")}};
 const criarPedido=async(e:any)=>{e.preventDefault();const itens=pedidoItens.filter(i=>i.material_id).map(i=>({material_id:Number(i.material_id),tamanho:i.tamanho||null,quantidade:inteiro(i.quantidade)}));if(!itens.length){setPedidoErro("Adicione pelo menos um material.");return}if(pedidoItens.some(i=>i.material_id&&mat(Number(i.material_id))?.controla_tamanho&&!i.tamanho)){setPedidoErro("Selecione o tamanho dos materiais que exigem tamanho.");return}setPedidoErro("");try{await api.post("/materiais/pedidos",{itens,observacao:observacao||null});setPedidoItens([{material_id:"",tamanho:"",quantidade:"1"}]);setObservacao("");carregar()}catch(e:any){setPedidoErro(e?.response?.data?.detail||"Erro ao criar pedido.")}};
 const abrirAtender=(p:Pedido,i:Item)=>{const m=mat(i.material_enviado_id||i.material_solicitado_id);setPedidoErro("");setAtenderModal({pedido:p,item:i});setAtenderForm({quantidade:String(inteiro(i.quantidade_enviada||i.quantidade_solicitada)),material_id:String(i.material_enviado_id||i.material_solicitado_id),tamanho:i.tamanho_enviado||i.tamanho_solicitado||m?.tamanhos[0]?.tamanho||"",motivo:i.motivo_substituicao||""})};
 const salvarAtendimento=async()=>{if(!atenderModal)return;const original=atenderModal.item.material_solicitado_id,escolhido=Number(atenderForm.material_id);try{await api.put(`/materiais/pedidos/${atenderModal.pedido.id}/itens/${atenderModal.item.id}`,{quantidade_enviada:inteiro(atenderForm.quantidade),material_enviado_id:escolhido===original?null:escolhido,tamanho_enviado:mat(escolhido)?.controla_tamanho?atenderForm.tamanho:null,motivo_substituicao:escolhido===original?null:atenderForm.motivo});setAtenderModal(null);carregar()}catch(e:any){setPedidoErro(e?.response?.data?.detail||"Erro ao atender item.")}};
 const abrirConcluir=(p:Pedido)=>{setPedidoErro("");setMotivoParcial("");setConcluirModal(p)}; const salvarConclusao=async()=>{if(!concluirModal)return;const parcial=concluirModal.itens.some(i=>n(i.quantidade_enviada)<n(i.quantidade_solicitada));if(parcial&&!motivoParcial.trim()){setPedidoErro("Informe o motivo para concluir o pedido parcial.");return}try{await api.post(`/materiais/pedidos/${concluirModal.id}/concluir`,{motivo_parcial:parcial?motivoParcial:null});setConcluirModal(null);carregar()}catch(e:any){setPedidoErro(e?.response?.data?.detail||"Erro ao concluir pedido.")}};
 const imprimir=(p:Pedido)=>{const w=window.open("","_blank","width=900,height=700");if(!w)return;const linhas=p.itens.map(i=>`<tr><td>${nomeMaterial(i.material_solicitado_id)}</td><td>${i.tamanho_solicitado||"—"}</td><td>${inteiro(i.quantidade_solicitada)}</td><td>☐</td></tr>`).join("");w.document.write(`<html><head><title>Pedido ${p.id}</title><style>body{font-family:Arial;padding:30px;color:#111}h1{font-size:22px}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border:1px solid #999;padding:10px;text-align:left}.meta{margin:8px 0}.assinatura{margin-top:50px}</style></head><body><h1>UNIDAL — PEDIDO DE MATERIAL Nº ${p.id}</h1><div class="meta"><b>Data:</b> ${new Date(p.criado_em).toLocaleString("pt-PT")}</div><div class="meta"><b>Solicitante:</b> Utilizador #${p.solicitante_id}</div><div class="meta"><b>Estado:</b> ${p.status}</div>${p.observacao?`<div class="meta"><b>Observação:</b> ${p.observacao}</div>`:""}<table><thead><tr><th>Material</th><th>Tamanho</th><th>Quantidade</th><th>Separado</th></tr></thead><tbody>${linhas}</tbody></table><div class="assinatura">Separado por: __________________________ &nbsp;&nbsp; Data: ____/____/______</div></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),250)};
 return <div className="p-4 md:p-6 space-y-6">
  <div><h1 className="text-2xl font-bold text-gray-800 flex items-center gap-2"><Warehouse size={26}/>Armazém</h1><p className="text-gray-500">Pedidos de materiais, preparação e controle de estoque.</p></div>{erro&&<div className="rounded border border-red-200 bg-red-50 p-3 text-red-700">{erro}</div>}
  {responsavel&&alertas.length>0&&<div className="rounded-lg border border-amber-200 bg-amber-50 p-4"><b>Estoque baixo:</b> {alertas.map(m=>m.nome).join(", ")}</div>}
  <div className="grid gap-6 xl:grid-cols-2">
   {chefe&&<form onSubmit={criarPedido} className="rounded-lg bg-white p-5 shadow"><h2 className="mb-4 font-semibold flex gap-2"><ClipboardList size={20}/>Novo pedido</h2>{pedidoErro&&!atenderModal&&!concluirModal&&<div className="mb-3 rounded bg-red-50 p-3 text-sm text-red-700">{pedidoErro}</div>}{pedidoItens.map((it,idx)=>{const m=mat(Number(it.material_id));return <div key={idx} className="mb-3 grid gap-2 md:grid-cols-[1fr_140px_110px_35px]"><MaterialSearch materiais={materiais} value={it.material_id} onChange={id=>setPedidoItens(v=>v.map((x,j)=>j===idx?{...x,material_id:id,tamanho:""}:x))}/>{m?.controla_tamanho?<select required className="border rounded px-3 py-2" value={it.tamanho} onChange={e=>setPedidoItens(v=>v.map((x,j)=>j===idx?{...x,tamanho:e.target.value}:x))}><option value="">Tamanho</option>{m.tamanhos.map(t=><option key={t.id} value={t.tamanho}>{t.tamanho}</option>)}</select>:<div className="hidden md:block"/>}<input className="border rounded px-3 py-2" type="number" min="1" step="1" value={it.quantidade} onChange={e=>setPedidoItens(v=>v.map((x,j)=>j===idx?{...x,quantidade:e.target.value}:x))}/><button type="button" className="text-red-500" onClick={()=>setPedidoItens(v=>v.filter((_,j)=>j!==idx))}>×</button></div>})}<button type="button" className="text-indigo-600 text-sm" onClick={()=>setPedidoItens(v=>[...v,{material_id:"",tamanho:"",quantidade:"1"}])}>+ Adicionar item</button><textarea className="mt-3 w-full border rounded p-2" placeholder="Observação do pedido (opcional)" value={observacao} onChange={e=>setObservacao(e.target.value)}/><button className="mt-3 rounded bg-indigo-600 px-4 py-2 text-white">Enviar pedido</button></form>}
   {responsavel&&<form onSubmit={criarMaterial} className="rounded-lg bg-white p-5 shadow"><h2 className="mb-1 font-semibold flex gap-2"><PackagePlus size={20}/>Cadastrar novo material</h2><p className="mb-4 text-sm text-gray-500">Para botas e roupas, marque “Controlar por tamanho”.</p><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Nome do material<input required className="mt-1 w-full border rounded px-3 py-2 font-normal" placeholder="Ex.: Botas de segurança" value={novoMaterial.nome} onChange={e=>setNovoMaterial({...novoMaterial,nome:e.target.value})}/></label><label className="text-sm font-medium">Unidade de medida<input required className="mt-1 w-full border rounded px-3 py-2 font-normal" value={novoMaterial.unidade} onChange={e=>setNovoMaterial({...novoMaterial,unidade:e.target.value})}/></label><label className="flex items-center gap-2 text-sm font-medium sm:col-span-2"><input type="checkbox" checked={novoMaterial.controla_tamanho} onChange={e=>setNovoMaterial({...novoMaterial,controla_tamanho:e.target.checked})}/>Controlar por tamanho</label>{novoMaterial.controla_tamanho?<label className="text-sm font-medium sm:col-span-2">Tamanhos disponíveis<input required className="mt-1 w-full border rounded px-3 py-2 font-normal" placeholder="Ex.: 39, 40, 41, 42 ou S, M, L, XL" value={novoMaterial.tamanhos} onChange={e=>setNovoMaterial({...novoMaterial,tamanhos:e.target.value})}/><span className="text-xs text-gray-500">Separe os tamanhos por vírgula.</span></label>:<label className="text-sm font-medium">Quantidade inicial<input type="number" min="0" step="1" className="mt-1 w-full border rounded px-3 py-2 font-normal" value={novoMaterial.estoque_inicial} onChange={e=>setNovoMaterial({...novoMaterial,estoque_inicial:e.target.value})}/></label>}<label className="text-sm font-medium">Estoque mínimo<input type="number" min="0" step="1" className="mt-1 w-full border rounded px-3 py-2 font-normal" value={novoMaterial.estoque_minimo} onChange={e=>setNovoMaterial({...novoMaterial,estoque_minimo:e.target.value})}/></label></div><button className="mt-4 rounded bg-indigo-600 px-4 py-2 text-white">Cadastrar novo material</button></form>}
  </div>
  {responsavel&&<section className="rounded-lg bg-white p-5 shadow"><div className="mb-4 flex justify-between gap-3"><div><h2 className="font-semibold flex gap-2"><Boxes size={20}/>Estoque</h2><p className="text-sm text-gray-500">{materiaisFiltrados.length} materiais encontrados</p></div><input className="w-72 border rounded px-3 py-2" placeholder="Pesquisar material..." value={buscaEstoque} onChange={e=>{setBuscaEstoque(e.target.value);setPaginaEstoque(1)}}/></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Material</th><th>Unidade</th><th>Físico</th><th>Disponível</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{materiaisPagina.map(m=><tr key={m.id} className="border-b align-top"><td className="p-2 font-medium">{m.nome}{m.controla_tamanho&&<div className="mt-1 text-xs font-normal text-gray-500">{m.tamanhos.map(t=>`${t.tamanho}: ${inteiro(t.estoque_disponivel)}`).join(" · ")}</div>}</td><td>{m.unidade}</td><td>{inteiro(m.estoque_fisico)}</td><td>{inteiro(m.estoque_disponivel)}</td><td>{alertas.some(a=>a.id===m.id)?<span className="text-amber-700 font-medium">Baixo</span>:"Normal"}</td><td className="py-2 whitespace-nowrap"><button className="mr-3 font-medium text-emerald-700" onClick={()=>abrirEstoqueModal("entrada",m)}>+ Entrada</button><button className="mr-3 text-indigo-600" onClick={()=>abrirEstoqueModal("editar",m)}>Editar</button><button className="text-gray-600" onClick={()=>abrirEstoqueModal("ajustar",m)}>Ajustar</button></td></tr>)}</tbody></table></div><div className="mt-4 flex justify-between text-sm"><button disabled={paginaEstoque<=1} className="rounded border px-3 py-1 disabled:opacity-40" onClick={()=>setPaginaEstoque(p=>p-1)}>Anterior</button><span>Página {paginaEstoque} de {totalPaginas}</span><button disabled={paginaEstoque>=totalPaginas} className="rounded border px-3 py-1 disabled:opacity-40" onClick={()=>setPaginaEstoque(p=>p+1)}>Próxima</button></div></section>}
  <Modal open={!!estoqueModal} title={estoqueModal?.tipo==="entrada"?"Entrada de estoque":estoqueModal?.tipo==="editar"?"Editar material":"Ajustar inventário"} onClose={()=>setEstoqueModal(null)} footer={<><button onClick={()=>setEstoqueModal(null)} className="rounded border px-4 py-2">Cancelar</button><button onClick={salvarEstoqueModal} className="rounded bg-indigo-600 px-4 py-2 text-white">Guardar</button></>}>{estoqueErro&&<div className="mb-3 bg-red-50 p-3 text-red-700">{estoqueErro}</div>}{estoqueModal?.material.controla_tamanho&&estoqueModal.tipo!=="editar"&&<label className="block mb-4 text-sm font-medium">Tamanho<select className="mt-1 w-full rounded border px-3 py-2" value={estoqueForm.tamanho} onChange={e=>setEstoqueForm({...estoqueForm,tamanho:e.target.value,quantidade:estoqueModal.tipo==="ajustar"?String(inteiro(estoqueModal.material.tamanhos.find(t=>t.tamanho===e.target.value)?.estoque_fisico||0)):estoqueForm.quantidade})}>{estoqueModal.material.tamanhos.map(t=><option key={t.id}>{t.tamanho}</option>)}</select></label>}{estoqueModal?.tipo==="entrada"&&<label className="block text-sm font-medium">Quantidade recebida<input type="number" min="1" step="1" className="mt-1 w-full rounded border px-3 py-2" value={estoqueForm.quantidade} onChange={e=>setEstoqueForm({...estoqueForm,quantidade:e.target.value})}/></label>}{estoqueModal?.tipo==="editar"&&<div className="space-y-3"><label className="block">Nome<input className="w-full border rounded p-2" value={estoqueForm.nome} onChange={e=>setEstoqueForm({...estoqueForm,nome:e.target.value})}/></label><label className="block">Unidade<input className="w-full border rounded p-2" value={estoqueForm.unidade} onChange={e=>setEstoqueForm({...estoqueForm,unidade:e.target.value})}/></label></div>}{estoqueModal?.tipo==="ajustar"&&<div className="space-y-3"><label className="block">Quantidade física<input type="number" min="0" step="1" className="w-full border rounded p-2" value={estoqueForm.quantidade} onChange={e=>setEstoqueForm({...estoqueForm,quantidade:e.target.value})}/></label><label className="block">Motivo<input className="w-full border rounded p-2" value={estoqueForm.motivo} onChange={e=>setEstoqueForm({...estoqueForm,motivo:e.target.value})}/></label></div>}</Modal>
  <Modal open={!!atenderModal} title="Atender item do pedido" onClose={()=>setAtenderModal(null)} footer={<><button onClick={()=>setAtenderModal(null)} className="rounded border px-4 py-2">Cancelar</button><button onClick={salvarAtendimento} className="rounded bg-indigo-600 px-4 py-2 text-white">Guardar atendimento</button></>}>{pedidoErro&&<div className="mb-3 bg-red-50 p-3 text-red-700">{pedidoErro}</div>}<div className="space-y-4"><label className="block">Quantidade enviada<input type="number" min="0" step="1" className="w-full border rounded p-2" value={atenderForm.quantidade} onChange={e=>setAtenderForm({...atenderForm,quantidade:e.target.value})}/></label><label className="block">Material enviado<select className="w-full border rounded p-2" value={atenderForm.material_id} onChange={e=>{const m=mat(Number(e.target.value));setAtenderForm({...atenderForm,material_id:e.target.value,tamanho:m?.tamanhos[0]?.tamanho||""})}}>{materiais.map(m=><option key={m.id} value={m.id}>{m.nome}</option>)}</select></label>{mat(Number(atenderForm.material_id))?.controla_tamanho&&<label className="block">Tamanho<select className="w-full border rounded p-2" value={atenderForm.tamanho} onChange={e=>setAtenderForm({...atenderForm,tamanho:e.target.value})}>{mat(Number(atenderForm.material_id))?.tamanhos.map(t=><option key={t.id}>{t.tamanho}</option>)}</select></label>}{atenderModal&&Number(atenderForm.material_id)!==atenderModal.item.material_solicitado_id&&<label className="block">Motivo da substituição<input className="w-full border rounded p-2" value={atenderForm.motivo} onChange={e=>setAtenderForm({...atenderForm,motivo:e.target.value})}/></label>}</div></Modal>
  <Modal open={!!concluirModal} title="Concluir pedido" onClose={()=>setConcluirModal(null)} footer={<><button onClick={()=>setConcluirModal(null)} className="rounded border px-4 py-2">Cancelar</button><button onClick={salvarConclusao} className="rounded bg-emerald-600 px-4 py-2 text-white">Concluir pedido</button></>}>{concluirModal?.itens.some(i=>n(i.quantidade_enviada)<n(i.quantidade_solicitada))?<label>Motivo da conclusão parcial<textarea className="w-full border rounded p-2" value={motivoParcial} onChange={e=>setMotivoParcial(e.target.value)}/></label>:<p>Todos os itens foram atendidos.</p>}</Modal>
  <section className="rounded-lg bg-white p-5 shadow"><h2 className="mb-4 font-semibold">Pedidos</h2><div className="space-y-4">{pedidos.map(p=><div key={p.id} className="rounded border p-4"><div className="flex flex-wrap justify-between gap-2"><div><b>Pedido #{p.id}</b> <span className="ml-2 text-sm text-gray-500">{p.status}</span></div><div className="flex gap-2"><button onClick={()=>imprimir(p)} className="flex items-center gap-1 rounded border px-3 py-1 text-sm"><Printer size={15}/>Imprimir</button>{responsavel&&p.status!=="CONCLUIDO"&&<button onClick={()=>abrirConcluir(p)} className="rounded bg-emerald-600 px-3 py-1 text-sm text-white">Concluir pedido</button>}</div></div>{p.observacao&&<p className="mt-2 text-sm text-gray-600">{p.observacao}</p>}<table className="mt-3 w-full text-sm"><thead><tr className="border-b text-left"><th>Solicitado</th><th>Tamanho</th><th>Qtd.</th><th>Enviado</th><th>Tamanho</th><th>Qtd.</th>{responsavel&&<th>Ação</th>}</tr></thead><tbody>{p.itens.map(i=><tr key={i.id} className="border-b"><td className="py-2">{nomeMaterial(i.material_solicitado_id)}</td><td>{i.tamanho_solicitado||"—"}</td><td>{inteiro(i.quantidade_solicitada)}</td><td>{i.material_enviado_id?nomeMaterial(i.material_enviado_id):"—"}</td><td>{i.tamanho_enviado||"—"}</td><td>{inteiro(i.quantidade_enviada)}</td>{responsavel&&<td><button disabled={p.status==="CONCLUIDO"} onClick={()=>abrirAtender(p,i)} className="text-indigo-600 disabled:text-gray-300">Atender</button></td>}</tr>)}</tbody></table></div>)}</div></section>
 </div>
};
export default Estaleiro;
